import json
import sqlite3
import time
from typing import List, Tuple
from src.discovery.models import CanonicalJob
from src.core.repositories.base import BaseRepository
from src.core.repositories.interfaces import IJobRepository

class JobRepository(BaseRepository, IJobRepository):
    # Workday-sourced jobs store a bare company_id ("revvity") while
    # company_identities uses a domain-derived scheme ("revvity-com-2a0f05")
    # generated by the discovery/canonicalization pipeline for every other
    # provider — a direct equality join misses ~94% of Workday's 333k+
    # active jobs (confirmed live: 19,363/333,784 matched), which meant no
    # domain -> no logo, but also no proper company canonicalization for
    # the largest single provider by job count. LATERAL + LIMIT 1 (not a
    # plain second LEFT JOIN) so a company_id that happens to prefix-match
    # more than one identities row can't duplicate the job row.
    # Range condition (not LIKE) so the planner can push this into an index
    # scan on company_identities even though the prefix is a correlated
    # column, not a constant -- LIKE with a non-constant pattern can't be
    # rewritten into a range scan and falls back to a per-row Seq Scan.
    # Uses ~>=~/~<~ (pattern-ops comparison operators) rather than plain
    # >=/< because the idx_company_identities_id_pattern text_pattern_ops
    # index only accelerates those, and because plain >=/< under the
    # database's default (non-C) collation treats '-' as low-weight and
    # sorts "alight-com-x" before "alight-" itself, breaking the range.
    _COMPANY_JOIN = """
        LEFT JOIN company_identities i ON n.company_id = i.company_id
        LEFT JOIN LATERAL (
            SELECT canonical_name, domain FROM company_identities
            WHERE i.company_id IS NULL
              AND company_id ~>=~ (n.company_id || '-')
              AND company_id ~<~  (n.company_id || '.')
            LIMIT 1
        ) i2 ON TRUE
    """

    def _init_db(self):
        # Use existing normalized_jobs table created by migrations
        pass

    def _load_profile(self, conn, user_id: str | None):
        """
        Builds the CandidateProfile for hard-reject/intent scoring from the
        logged-in user's real `user_career_profiles.profile_data`, keyed by
        user_id — NOT the old static single-tenant YAML config, which scored
        every candidate against one hardcoded profile.
        """
        from src.discovery.jie.candidate_profile import CandidateProfile

        cache = getattr(self, "_profile_cache", None)
        if cache is None:
            cache = self._profile_cache = {}
        if user_id in cache and (cache[user_id].skills or cache[user_id].target_roles):
            return cache[user_id]

        profile = CandidateProfile()
        if user_id:
            try:
                p = conn.dialect.placeholder()
                row = conn.execute(
                    f"SELECT profile_data FROM public.user_career_profiles WHERE user_id = {p}",
                    (user_id,),
                ).fetchone()
                if row:
                    raw = row["profile_data"] if hasattr(row, "keys") else row[0]
                    if isinstance(raw, str):
                        raw = json.loads(raw)
                    if raw:
                        profile = CandidateProfile.from_profile_data(raw)
            except Exception:
                profile = CandidateProfile()

        if profile.skills or profile.target_roles:
            cache[user_id] = profile
        return profile

    @property
    def _hard_reject(self):
        if not hasattr(self, "_cached_hard_reject"):
            from src.discovery.hard_reject_filter import HardRejectFilter
            self._cached_hard_reject = HardRejectFilter()
        return self._cached_hard_reject

    @property
    def _intent_filter(self):
        if not hasattr(self, "_cached_intent_filter"):
            from src.discovery.intent_filter import IntentFilter
            self._cached_intent_filter = IntentFilter()
        return self._cached_intent_filter

    # Below this many precomputed rows, a user's background-scored coverage
    # isn't wide enough to trust as "their real top matches" yet (e.g. right
    # after signup, before JobScoringWorker has caught up) — fall back to
    # the bounded live-scoring path instead so they see something immediately.
    _PRECOMPUTED_MIN_COVERAGE = 20

    def get_jobs_from_precomputed(self, page: int, page_size: int, user_id: str, min_score: float = None,
                                   location: str = None, provider: str = None, company: str = None,
                                   title: str = None, remote_type: str = None, employment_type: str = None,
                                   min_salary: float = None, pipeline: str = "A", conn=None):
        """
        Serves scored jobs from user_job_scores (populated by the background
        JobScoringWorker against the full active-jobs pool) instead of live-
        scoring a bounded recent-jobs window per request. Returns None if
        this user doesn't have enough precomputed coverage yet, signaling
        the caller to fall back to the live path.
        """
        from src.api.db import json_extract
        import json

        p = conn.dialect.placeholder()
        json_company = json_extract('n.raw_payload_json', '$.company')

        where_clause = f"""
            FROM public.user_job_scores s
            JOIN normalized_jobs n ON n.job_id = s.job_id
            {self._COMPANY_JOIN}
            WHERE s.user_id = {p} AND s.passed_hard_reject = TRUE AND n.status = 'ACTIVE'
        """
        params = [user_id]

        job_board_providers = ["linkedin", "google_jobs", "wellfound", "indeed"]
        provider_placeholders = ",".join([p] * len(job_board_providers))
        if pipeline == "B":
            where_clause += f" AND n.provider IN ({provider_placeholders})"
        else:
            where_clause += f" AND n.provider NOT IN ({provider_placeholders})"
        params.extend(job_board_providers)

        if provider:
            where_clause += f" AND n.provider = {p}"
            params.append(provider)
        if company:
            where_clause += f" AND (n.company_id LIKE {p} OR COALESCE(i.canonical_name, i2.canonical_name, {json_company}, '') LIKE {p})"
            params.extend([f"%{company}%", f"%{company}%"])
        if title:
            where_clause += f" AND n.title LIKE {p}"
            params.append(f"%{title}%")
        if location:
            where_clause += f" AND n.location LIKE {p}"
            params.append(f"%{location}%")
        if remote_type:
            where_clause += f" AND n.remote_type = {p}"
            params.append(remote_type)
        if employment_type:
            where_clause += f" AND n.employment_type = {p}"
            params.append(employment_type)
        if min_salary is not None:
            where_clause += f" AND (n.salary_max >= {p} OR n.salary_min >= {p})"
            params.extend([min_salary, min_salary])
        if min_score is not None:
            where_clause += f" AND s.job_score >= {p}"
            params.append(min_score)

        count_row = conn.execute(f"SELECT COUNT(*) as cnt {where_clause}", tuple(params)).fetchone()
        total_scored = count_row["cnt"] if count_row else 0
        if total_scored < self._PRECOMPUTED_MIN_COVERAGE:
            return None

        limit = conn.dialect.create_limit(page_size)
        offset = (page - 1) * page_size
        select_clause = f"""
            SELECT COALESCE(i.canonical_name, i2.canonical_name, {json_company}, n.company_id) AS canonical_name,
                   COALESCE(i.domain, i2.domain) AS company_domain,
                   n.job_id, n.title, n.provider,
                   n.location, n.remote_type as remote, n.employment_type,
                   n.salary_min, n.salary_max, n.posted_at, n.apply_url,
                   n.description, n.status,
                   s.job_score, s.intent_score, s.score_breakdown
        """
        query = f"{select_clause} {where_clause} ORDER BY s.job_score DESC, n.posted_at DESC {limit} OFFSET {offset}"
        c = conn.execute(query, tuple(params))
        rows = [dict(row) if hasattr(row, 'keys') else dict(zip([col[0] for col in c.description], row)) for row in c.fetchall()]
        for r in rows:
            try:
                r["score_breakdown"] = json.loads(r["score_breakdown"] or "[]")
            except Exception:
                r["score_breakdown"] = []
            r["match_score"] = 0.0
            r["priority_score"] = 0.0
            r["scoring_confidence"] = 0.0
            r["recommendation_reason"] = ""
            r["application_status"] = "NEW"
        return rows

    def get_jobs(self, page: int=1, page_size: int=50, provider: str=None, company: str=None, title: str=None, status: str="ACTIVE", min_score: float=None, pipeline: str="A", location: str=None, remote_type: str=None, employment_type: str=None, seniority: str=None, min_salary: float=None, sort_by: str="newest", user_id: str=None, tx=None):
        from src.api.db import json_extract
        import json
        with self.transaction() as conn:
            if sort_by == "score" and user_id:
                precomputed = self.get_jobs_from_precomputed(
                    page=page, page_size=page_size, user_id=user_id, min_score=min_score,
                    location=location, provider=provider, company=company, title=title,
                    remote_type=remote_type, employment_type=employment_type,
                    min_salary=min_salary, pipeline=pipeline, conn=conn,
                )
                if precomputed is not None:
                    return precomputed

            p = conn.dialect.placeholder()
            json_company = json_extract('n.raw_payload_json', '$.company')
            base_query = f"""
                SELECT COALESCE(i.canonical_name, i2.canonical_name, {json_company}, n.company_id) AS canonical_name,
                       COALESCE(i.domain, i2.domain) AS company_domain,
                       n.job_id, n.title, n.provider,
                       n.location, n.remote_type as remote, n.employment_type,
                       n.salary_min, n.salary_max, n.posted_at, n.apply_url,
                       n.description, n.status
                FROM normalized_jobs n
                {self._COMPANY_JOIN}
                WHERE n.status = {p}
            """
            params = [status]

            job_board_providers = ["linkedin", "google_jobs", "wellfound", "indeed"]
            provider_placeholders = ",".join([p] * len(job_board_providers))
            if pipeline == "B":
                base_query += f" AND n.provider IN ({provider_placeholders})"
                params.extend(job_board_providers)
            else:
                base_query += f" AND n.provider NOT IN ({provider_placeholders})"
                params.extend(job_board_providers)

            if provider:
                base_query += f" AND n.provider = {p}"
                params.append(provider)
            if company:
                base_query += f" AND (n.company_id LIKE {p} OR COALESCE(i.canonical_name, i2.canonical_name, {json_company}, '') LIKE {p})"
                params.extend([f"%{company}%", f"%{company}%"])
            if title:
                base_query += f" AND n.title LIKE {p}"
                params.append(f"%{title}%")
            if location:
                base_query += f" AND n.location LIKE {p}"
                params.append(f"%{location}%")
            if remote_type:
                base_query += f" AND n.remote_type = {p}"
                params.append(remote_type)
            if employment_type:
                base_query += f" AND n.employment_type = {p}"
                params.append(employment_type)
            if min_salary is not None:
                base_query += f" AND (n.salary_max >= {p} OR n.salary_min >= {p})"
                params.extend([min_salary, min_salary])

            # Bound the candidate set to the most recent N active jobs before
            # windowing/ranking. Without this, the per-company window function
            # below has to sort the entire active-jobs table (1.4M+ rows,
            # ~25s) just to produce a 2000-row page — status='ACTIVE' alone
            # matches ~99% of the table so it can't narrow anything down.
            # idx_normalized_jobs_active_posted_at (status='ACTIVE', posted_at
            # DESC) lets Postgres satisfy this ORDER BY + LIMIT with an index
            # scan instead of a full sort (~25s -> ~0.6s measured). 10k is
            # comfortably larger than per_company_cap * any realistic company
            # count feeding the final 2000-row cap.
            candidate_limit = conn.dialect.create_limit(10000)
            base_query += f" ORDER BY n.posted_at DESC {candidate_limit}"

            # Cap how many of the initial fetch can come from any one company.
            # Without this, a franchise/retail poster that bulk-syncs thousands
            # of store-level listings (e.g. 24k+ active jobs from one chain)
            # dominates the ORDER BY posted_at DESC window before hard-reject
            # or scoring ever runs, so every visible result is the same company.
            per_company_cap = 5
            query = f"""
                SELECT canonical_name, company_domain, job_id, title, 0 as job_score, provider,
                       '{{}}' as score_breakdown, 0.0 as match_score, 0.0 as priority_score,
                       0.0 as scoring_confidence, '' as recommendation_reason,
                       'NEW' as application_status,
                       location, remote, employment_type, salary_min, salary_max,
                       posted_at, apply_url, description, status
                FROM (
                    SELECT b.*, ROW_NUMBER() OVER (
                        PARTITION BY b.canonical_name ORDER BY b.posted_at DESC
                    ) AS company_rank
                    FROM ({base_query}) b
                ) ranked
                WHERE company_rank <= {per_company_cap}
            """
            limit = conn.dialect.create_limit(2000)
            # company_rank first so the fetch itself is interleaved across
            # companies (rank-1 job from every company, then rank-2, ...) —
            # otherwise a stable sort on tied intent_scores later would still
            # let one company's jobs cluster together in the visible results.
            query += f" ORDER BY company_rank ASC, posted_at DESC {limit}"
            c = conn.execute(query, tuple(params))
            raw_jobs = [dict(row) if hasattr(row, 'keys') else dict(zip([col[0] for col in c.description], row)) for row in c.fetchall()]

            for j in raw_jobs:
                try:
                    j["score_breakdown"] = json.loads(j["score_breakdown"] or "[]")
                except Exception:
                    j["score_breakdown"] = []

            profile = self._load_profile(conn, user_id)
            passed, rejected, _ = self._hard_reject.filter_batch(raw_jobs, profile)
            scored_jobs, _ = self._intent_filter.score_batch(passed, profile)

            # job_score was a hardcoded 0 placeholder in the SQL — populate it
            # for real from the computed intent_score so every consumer of
            # this API (not just the one screen that happened to prefer
            # intent_score client-side) shows an actual match percentage.
            for j in scored_jobs:
                j["job_score"] = round(j.get("intent_score", 0.0) * 100)

            if min_score is not None:
                scored_jobs = [j for j in scored_jobs if j.get("intent_score", 0.0) >= min_score / 100.0]

            if sort_by == "score":
                scored_jobs.sort(key=lambda x: x.get("intent_score", 0.0), reverse=True)
            else:
                scored_jobs.sort(key=lambda x: (x.get("posted_at") or "", x.get("intent_score", 0.0)), reverse=True)

            offset = (page - 1) * page_size
            return scored_jobs[offset : offset + page_size]

    # ── Background scoring (JobScoringWorker) ────────────────────────────────
    # Precomputes user_job_scores against the *entire* active-jobs pool
    # incrementally, so get_jobs_from_precomputed above can serve "best out
    # of 1.44M" reads instantly instead of live-scoring a bounded recent
    # window per request.

    def get_users_needing_scoring(self, tx=None) -> List[Tuple[str, str]]:
        """Every user with a career profile — (user_id, profile_updated_at as text)."""
        with self.transaction() as conn:
            rows = conn.execute(
                "SELECT user_id, updated_at FROM public.user_career_profiles"
            ).fetchall()
            return [
                (
                    (r["user_id"] if hasattr(r, "keys") else r[0]),
                    str(r["updated_at"] if hasattr(r, "keys") else r[1]),
                )
                for r in rows
            ]

    # Same two regex vocabularies HardRejectFilter's Rule 3 (senior keywords)
    # and Rule 6 (India/remote location) use, duplicated here deliberately
    # rather than imported -- this SQL filter is a coarse, APPROXIMATE
    # pre-filter, not a second source of truth. It only needs to be
    # conservative (never exclude a job HardRejectFilter would have passed);
    # it's fine if it's slightly looser than the Python rules (e.g. it
    # doesn't also check numbered/L-grade levels or the full geo-restricted-
    # remote signal list) since HardRejectFilter still runs, unchanged, on
    # whatever this lets through. The point is only to stop fetching+
    # evaluating jobs in Python that are obviously going to hard-reject on
    # the two checks that dominate real rejection counts (confirmed via
    # live worker logs: "Location mismatch" and "Senior-level role" together
    # account for ~75-80% of every batch's rejections).
    _SQL_SENIOR_TITLE_PATTERN = (
        r"\ysenior\y|\ysr\y|\ystaff\y|\yprincipal\y|\ylead\y|\ydirector\y|\yvp\y|"
        r"\yvice president\y|\yhead of\y|\yengineering manager\y|\ytechnical manager\y"
    )
    _SQL_INDIA_LOCATION_PATTERN = (
        r"\ybangalore\y|\ybengaluru\y|\ymumbai\y|\ypune\y|\yhyderabad\y|\ychennai\y|"
        r"\ydelhi\y|\yncr\y|\ygurgaon\y|\ygurugram\y|\ynoida\y|\ykolkata\y|\yahmedabad\y|\yindia\y"
    )
    _SQL_REMOTE_LOCATION_PATTERN = r"\yremote\y|\ywork from home\y|\ywfh\y"

    def get_unscored_job_batch(
        self,
        user_id: str,
        profile_updated_at: str,
        limit: int = 500,
        years_experience: int | None = None,
        preferred_locations: List[str] | None = None,
        tx=None,
    ) -> List[dict]:
        """
        Active jobs this user hasn't been scored against yet, or whose score
        predates their current profile (profile changed since last scored).
        Anti-joined against user_job_scores rather than OFFSET-paginated, so
        repeated calls naturally converge on full coverage without needing
        the caller to track a cursor.

        When years_experience/preferred_locations are supplied, also applies
        the SQL pre-filter described above -- callers that omit them get the
        unfiltered batch (e.g. the anti-join alone), same as before this was
        added.
        """
        with self.transaction() as conn:
            p = conn.dialect.placeholder()
            batch_limit = conn.dialect.create_limit(limit)
            params = [user_id, profile_updated_at]
            extra_where = ""

            if years_experience is not None and (years_experience or 0) < 5:
                extra_where += f" AND (n.title !~* {p})"
                params.append(self._SQL_SENIOR_TITLE_PATTERN)

            if preferred_locations is not None:
                location_clause = (
                    f"n.location ~* {p} OR n.location ~* {p} "
                    f"OR n.location IS NULL OR n.location = ''"
                )
                params.extend([self._SQL_INDIA_LOCATION_PATTERN, self._SQL_REMOTE_LOCATION_PATTERN])
                preferred = [pl.strip() for pl in preferred_locations if pl and pl.strip()]
                if preferred:
                    location_clause += f" OR n.location ILIKE ANY({p})"
                    params.append([f"%{pl}%" for pl in preferred])
                extra_where += f" AND ({location_clause})"

            query = f"""
                SELECT n.job_id, n.title, n.description, n.provider, n.status, n.location, n.apply_url
                FROM normalized_jobs n
                LEFT JOIN public.user_job_scores s
                    ON s.job_id = n.job_id AND s.user_id = {p}
                WHERE n.status = 'ACTIVE'
                  AND (s.job_id IS NULL OR s.profile_updated_at IS DISTINCT FROM {p}::timestamptz)
                  {extra_where}
                {batch_limit}
            """
            c = conn.execute(query, tuple(params))
            return [dict(row) if hasattr(row, 'keys') else dict(zip([col[0] for col in c.description], row)) for row in c.fetchall()]

    def store_job_scores(self, user_id: str, profile_updated_at: str, scored: List[dict], tx=None) -> None:
        """Upserts a batch of {job_id, job_score, intent_score, passed, reason, breakdown}."""
        import json
        if not scored:
            return
        with self.transaction() as conn:
            p = conn.dialect.placeholder()
            for row in scored:
                conn.execute(
                    f"""
                    INSERT INTO public.user_job_scores
                        (user_id, job_id, job_score, intent_score, passed_hard_reject,
                         rejection_reason, score_breakdown, profile_updated_at, scored_at)
                    VALUES ({p}, {p}, {p}, {p}, {p}, {p}, {p}, {p}::timestamptz, NOW())
                    ON CONFLICT (user_id, job_id) DO UPDATE SET
                        job_score = EXCLUDED.job_score,
                        intent_score = EXCLUDED.intent_score,
                        passed_hard_reject = EXCLUDED.passed_hard_reject,
                        rejection_reason = EXCLUDED.rejection_reason,
                        score_breakdown = EXCLUDED.score_breakdown,
                        profile_updated_at = EXCLUDED.profile_updated_at,
                        scored_at = NOW()
                    """,
                    (
                        user_id,
                        row["job_id"],
                        row["job_score"],
                        row["intent_score"],
                        row["passed_hard_reject"],
                        row.get("rejection_reason"),
                        json.dumps(row.get("score_breakdown") or []),
                        profile_updated_at,
                    ),
                )

    # ── Semantic (vector) matching ────────────────────────────────────────────
    # pgvector-backed nearest-neighbor search over normalized_jobs.embedding,
    # populated by embedding_backfill_worker.py. Complements (doesn't replace)
    # the hard-reject filter — ANN search finds semantically close jobs fast
    # across the full 1.4M+ pool, then the existing binary constraints
    # (experience, location, seniority) still get applied on that shortlist,
    # since embeddings alone don't understand "must have 5 years" as a hard
    # cutoff the way HardRejectFilter does.

    @staticmethod
    def _vector_literal(vec: List[float]) -> str:
        return "[" + ",".join(repr(float(x)) for x in vec) + "]"

    def get_jobs_missing_embedding(self, limit: int = 500, tx=None) -> List[dict]:
        with self.transaction() as conn:
            batch_limit = conn.dialect.create_limit(limit)
            c = conn.execute(
                f"""
                SELECT job_id, title, description FROM normalized_jobs
                WHERE status = 'ACTIVE' AND embedding IS NULL
                {batch_limit}
                """
            )
            return [dict(row) if hasattr(row, 'keys') else dict(zip([col[0] for col in c.description], row)) for row in c.fetchall()]

    def store_job_embeddings(self, job_id_to_vector: dict, tx=None) -> None:
        if not job_id_to_vector:
            return
        with self.transaction() as conn:
            p = conn.dialect.placeholder()
            for job_id, vec in job_id_to_vector.items():
                conn.execute(
                    f"UPDATE normalized_jobs SET embedding = {p}::vector WHERE job_id = {p}",
                    (self._vector_literal(vec), job_id),
                )

    def get_candidate_embedding(self, user_id: str, tx=None):
        """Returns the stored embedding vector (as a string) for this user's
        profile, or None if not computed yet."""
        with self.transaction() as conn:
            p = conn.dialect.placeholder()
            row = conn.execute(
                f"SELECT embedding::text as embedding FROM public.user_career_profiles WHERE user_id = {p}",
                (user_id,),
            ).fetchone()
            if row and row["embedding"]:
                return row["embedding"]
            return None

    def store_candidate_embedding(self, user_id: str, vec: List[float], tx=None) -> None:
        with self.transaction() as conn:
            p = conn.dialect.placeholder()
            conn.execute(
                f"UPDATE public.user_career_profiles SET embedding = {p}::vector WHERE user_id = {p}",
                (self._vector_literal(vec), user_id),
            )

    def get_jobs_by_vector_similarity(self, user_id: str, k: int = 500, tx=None) -> List[dict]:
        """
        ANN shortlist of the k jobs semantically closest to this candidate's
        profile embedding, across the *entire* active pool — not bounded by
        recency the way the live-scoring fallback path is. Returns raw job
        dicts (title/description/etc, no scoring applied yet); caller runs
        HardRejectFilter/IntentFilter on this shortlist same as any other
        batch, or serves it directly ordered by vector distance.
        """
        from src.api.db import json_extract
        embedding = self.get_candidate_embedding(user_id)
        if not embedding:
            return []

        with self.transaction() as conn:
            p = conn.dialect.placeholder()
            json_company = json_extract('n.raw_payload_json', '$.company')
            batch_limit = conn.dialect.create_limit(k)
            query = f"""
                SELECT COALESCE(i.canonical_name, i2.canonical_name, {json_company}, n.company_id) AS canonical_name,
                       COALESCE(i.domain, i2.domain) AS company_domain,
                       n.job_id, n.title, n.provider,
                       n.location, n.remote_type as remote, n.employment_type,
                       n.salary_min, n.salary_max, n.posted_at, n.apply_url,
                       n.description, n.status,
                       1 - (n.embedding <=> {p}::vector) AS vector_similarity
                FROM normalized_jobs n
                {self._COMPANY_JOIN}
                WHERE n.status = 'ACTIVE' AND n.embedding IS NOT NULL
                ORDER BY n.embedding <=> {p}::vector
                {batch_limit}
            """
            c = conn.execute(query, (embedding, embedding))
            return [dict(row) if hasattr(row, 'keys') else dict(zip([col[0] for col in c.description], row)) for row in c.fetchall()]

    def get_job(self, job_id: str, tx=None) -> dict | None:
        from src.api.db import json_extract
        import json
        with self.transaction() as conn:
            p = conn.dialect.placeholder()
            json_company = json_extract('n.raw_payload_json', '$.company')
            query = f"""
                SELECT COALESCE(i.canonical_name, i2.canonical_name, {json_company}, n.company_id) AS canonical_name,
                       COALESCE(i.domain, i2.domain) AS company_domain,
                       n.job_id, n.title, 0 as job_score, n.provider, '{{}}' as score_breakdown,
                       0.0 as match_score, 0.0 as priority_score, 0.0 as scoring_confidence,
                       '' as recommendation_reason, 'NEW' as application_status,
                       n.description, n.location, n.remote_type as remote,
                       n.salary_min, n.salary_max, n.apply_url, n.posted_at
                FROM normalized_jobs n
                {self._COMPANY_JOIN}
                WHERE n.job_id = {p}
            """
            c = conn.execute(query, (job_id,))
            row = c.fetchone()
            if not row:
                return None
            j = dict(row) if hasattr(row, 'keys') else dict(zip([col[0] for col in c.description], row))
            try:
                j["score_breakdown"] = json.loads(j["score_breakdown"] or "[]")
            except Exception:
                j["score_breakdown"] = []
            return j

    def upsert_and_diff(self, jobs: List[CanonicalJob], board_id: str, synced_at: float, tx=None) -> Tuple[int, int, int, int]:
        """
        Takes the new canonical jobs, diffs against existing active jobs for the board/company.
        Returns (inserted, updated, archived, previous_jobs).
        """
        inserted = 0
        updated = 0
        archived = 0
        
        if not jobs:
            return (0, 0, 0, 0)
            
        company_id = jobs[0].company_id

        # 1. Get all active job hashes for this company
        with self.get_connection() as conn:
            p = conn.dialect.placeholder()
            
            # Using dict row factory safely
            if hasattr(conn, 'row_factory'):
                conn.row_factory = sqlite3.Row
                
            cursor = conn.execute(f"SELECT job_hash FROM normalized_jobs WHERE company_id = {p} AND status = 'ACTIVE'", (company_id,))
            active_hashes = {row['job_hash'] if isinstance(row, dict) or hasattr(row, 'keys') else row[0] for row in cursor.fetchall()}
            
        current_hashes = set()
        
        with self.get_connection() as conn:
            p = conn.dialect.placeholder()
            upsert = conn.dialect.upsert(
                table="normalized_jobs",
                conflict_columns=["job_id"],
                update_columns=["title", "location", "apply_url", "description", "status", "raw_payload_json"]
            )
            
            for job in jobs:
                job_hash = job.identity.get_hash()
                current_hashes.add(job_hash)
                
                is_new = job_hash not in active_hashes
                if is_new:
                    inserted += 1
                else:
                    updated += 1
                    
                conn.execute(f"""
                    INSERT INTO normalized_jobs (
                        job_id, provider_job_id, company_id, provider, title, location, 
                        remote_type, employment_type, department, salary_min, salary_max, 
                        currency, posted_at, apply_url, description, job_hash, status,
                        raw_payload_json
                    ) VALUES (
                        {p}, {p}, {p}, {p}, {p}, {p},
                        {p}, {p}, {p}, {p}, {p},
                        {p}, {p}, {p}, {p}, {p}, 'ACTIVE',
                        {p}
                    )
                    {upsert}
                """, (
                    job_hash, job.identity.external_job_id or job_hash, job.company_id, job.identity.provider, job.title, job.location,
                    job.remote_type, job.employment_type, job.department, job.salary_min, job.salary_max,
                    job.salary_currency, job.posted_at, job.apply_url, job.description, job_hash,
                    json.dumps(job.raw_payload)
                ))
            
            # Identify archived jobs
            missing_hashes = active_hashes - current_hashes
            if missing_hashes:
                archived = len(missing_hashes)
                now = conn.dialect.current_timestamp()
                for h in missing_hashes:
                    conn.execute(f"UPDATE normalized_jobs SET status = 'CLOSED', closed_at = {now} WHERE job_hash = {p}", (h,))
            
        return (inserted, updated, archived, len(active_hashes))

    def load_cursor(self, provider_name: str, tx=None) -> str | None:
        with self.transaction() as conn:
            p = conn.dialect.placeholder()
            limit = conn.dialect.create_limit(1)
            row = conn.execute(
                f"""SELECT cursor FROM job_board_snapshots
                   WHERE provider = {p} AND status IN ('SUCCESS', 'PARTIAL')
                   ORDER BY synced_at DESC {limit}""",
                (provider_name,),
            ).fetchone()
            return row[0] if row else None

    def save_snapshot(
        self,
        provider_name: str,
        next_cursor: str | None,
        jobs_found: int,
        jobs_new: int,
        jobs_updated: int,
        companies_discovered: int,
        status: str,
        error: str | None,
        tx=None
    ):
        with self.transaction() as conn:
            p = conn.dialect.placeholder()
            now_ts = int(time.time())
            conn.execute(
                f"""INSERT INTO job_board_snapshots
                   (provider, synced_at, cursor, jobs_found, jobs_new,
                    jobs_updated, companies_discovered, status, error)
                   VALUES ({p}, {p}, {p}, {p}, {p}, {p}, {p}, {p}, {p})""",
                (
                    provider_name,
                    now_ts,
                    next_cursor,
                    jobs_found,
                    jobs_new,
                    jobs_updated,
                    companies_discovered,
                    status,
                    error,
                ),
            )
