/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MissionControlRouteImport } from './routes/mission-control'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MissionControlIndexRouteImport } from './routes/mission-control/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as MissionControlUnknownRouteImport } from './routes/mission-control/unknown'
import { Route as MissionControlTelemetryRouteImport } from './routes/mission-control/telemetry'
import { Route as MissionControlLeakageExplorerRouteImport } from './routes/mission-control/leakage-explorer'
import { Route as MissionControlDecisionEngineRouteImport } from './routes/mission-control/decision-engine'
import { Route as MissionControlCompanyReplayRouteImport } from './routes/mission-control/company-replay'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardResumeTailorRouteImport } from './routes/dashboard/resume-tailor'
import { Route as DashboardResumeRouteImport } from './routes/dashboard/resume'
import { Route as DashboardJobsRouteImport } from './routes/dashboard/jobs'
import { Route as DashboardCareerProfileRouteImport } from './routes/dashboard/career-profile'
import { Route as DashboardApplicationsRouteImport } from './routes/dashboard/applications'
import { Route as AboutProductRouteImport } from './routes/about/product'
import { Route as DashboardJobsJobIdRouteImport } from './routes/dashboard/jobs.$jobId'

const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionControlRoute = MissionControlRouteImport.update({
  id: '/mission-control',
  path: '/mission-control',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionControlIndexRoute = MissionControlIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MissionControlRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const MissionControlUnknownRoute = MissionControlUnknownRouteImport.update({
  id: '/unknown',
  path: '/unknown',
  getParentRoute: () => MissionControlRoute,
} as any)
const MissionControlTelemetryRoute = MissionControlTelemetryRouteImport.update({
  id: '/telemetry',
  path: '/telemetry',
  getParentRoute: () => MissionControlRoute,
} as any)
const MissionControlLeakageExplorerRoute =
  MissionControlLeakageExplorerRouteImport.update({
    id: '/leakage-explorer',
    path: '/leakage-explorer',
    getParentRoute: () => MissionControlRoute,
  } as any)
const MissionControlDecisionEngineRoute =
  MissionControlDecisionEngineRouteImport.update({
    id: '/decision-engine',
    path: '/decision-engine',
    getParentRoute: () => MissionControlRoute,
  } as any)
const MissionControlCompanyReplayRoute =
  MissionControlCompanyReplayRouteImport.update({
    id: '/company-replay',
    path: '/company-replay',
    getParentRoute: () => MissionControlRoute,
  } as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResumeTailorRoute = DashboardResumeTailorRouteImport.update({
  id: '/resume-tailor',
  path: '/resume-tailor',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResumeRoute = DashboardResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJobsRoute = DashboardJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCareerProfileRoute = DashboardCareerProfileRouteImport.update({
  id: '/career-profile',
  path: '/career-profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApplicationsRoute = DashboardApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => DashboardRoute,
} as any)
const AboutProductRoute = AboutProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => AboutRoute,
} as any)
const DashboardJobsJobIdRoute = DashboardJobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => DashboardJobsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/health': typeof HealthRoute
  '/legal': typeof LegalRoute
  '/mission-control': typeof MissionControlRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/upgrade': typeof UpgradeRoute
  '/about/product': typeof AboutProductRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/career-profile': typeof DashboardCareerProfileRoute
  '/dashboard/jobs': typeof DashboardJobsRouteWithChildren
  '/dashboard/resume': typeof DashboardResumeRoute
  '/dashboard/resume-tailor': typeof DashboardResumeTailorRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/mission-control/company-replay': typeof MissionControlCompanyReplayRoute
  '/mission-control/decision-engine': typeof MissionControlDecisionEngineRoute
  '/mission-control/leakage-explorer': typeof MissionControlLeakageExplorerRoute
  '/mission-control/telemetry': typeof MissionControlTelemetryRoute
  '/mission-control/unknown': typeof MissionControlUnknownRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/mission-control/': typeof MissionControlIndexRoute
  '/dashboard/jobs/$jobId': typeof DashboardJobsJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/health': typeof HealthRoute
  '/legal': typeof LegalRoute
  '/onboarding': typeof OnboardingRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/upgrade': typeof UpgradeRoute
  '/about/product': typeof AboutProductRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/career-profile': typeof DashboardCareerProfileRoute
  '/dashboard/jobs': typeof DashboardJobsRouteWithChildren
  '/dashboard/resume': typeof DashboardResumeRoute
  '/dashboard/resume-tailor': typeof DashboardResumeTailorRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/mission-control/company-replay': typeof MissionControlCompanyReplayRoute
  '/mission-control/decision-engine': typeof MissionControlDecisionEngineRoute
  '/mission-control/leakage-explorer': typeof MissionControlLeakageExplorerRoute
  '/mission-control/telemetry': typeof MissionControlTelemetryRoute
  '/mission-control/unknown': typeof MissionControlUnknownRoute
  '/dashboard': typeof DashboardIndexRoute
  '/mission-control': typeof MissionControlIndexRoute
  '/dashboard/jobs/$jobId': typeof DashboardJobsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/health': typeof HealthRoute
  '/legal': typeof LegalRoute
  '/mission-control': typeof MissionControlRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/upgrade': typeof UpgradeRoute
  '/about/product': typeof AboutProductRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/career-profile': typeof DashboardCareerProfileRoute
  '/dashboard/jobs': typeof DashboardJobsRouteWithChildren
  '/dashboard/resume': typeof DashboardResumeRoute
  '/dashboard/resume-tailor': typeof DashboardResumeTailorRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/mission-control/company-replay': typeof MissionControlCompanyReplayRoute
  '/mission-control/decision-engine': typeof MissionControlDecisionEngineRoute
  '/mission-control/leakage-explorer': typeof MissionControlLeakageExplorerRoute
  '/mission-control/telemetry': typeof MissionControlTelemetryRoute
  '/mission-control/unknown': typeof MissionControlUnknownRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/mission-control/': typeof MissionControlIndexRoute
  '/dashboard/jobs/$jobId': typeof DashboardJobsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/forgot-password'
    | '/health'
    | '/legal'
    | '/mission-control'
    | '/onboarding'
    | '/payment-success'
    | '/pricing'
    | '/privacy'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/upgrade'
    | '/about/product'
    | '/dashboard/applications'
    | '/dashboard/career-profile'
    | '/dashboard/jobs'
    | '/dashboard/resume'
    | '/dashboard/resume-tailor'
    | '/dashboard/settings'
    | '/mission-control/company-replay'
    | '/mission-control/decision-engine'
    | '/mission-control/leakage-explorer'
    | '/mission-control/telemetry'
    | '/mission-control/unknown'
    | '/dashboard/'
    | '/mission-control/'
    | '/dashboard/jobs/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/health'
    | '/legal'
    | '/onboarding'
    | '/payment-success'
    | '/pricing'
    | '/privacy'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/upgrade'
    | '/about/product'
    | '/dashboard/applications'
    | '/dashboard/career-profile'
    | '/dashboard/jobs'
    | '/dashboard/resume'
    | '/dashboard/resume-tailor'
    | '/dashboard/settings'
    | '/mission-control/company-replay'
    | '/mission-control/decision-engine'
    | '/mission-control/leakage-explorer'
    | '/mission-control/telemetry'
    | '/mission-control/unknown'
    | '/dashboard'
    | '/mission-control'
    | '/dashboard/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/forgot-password'
    | '/health'
    | '/legal'
    | '/mission-control'
    | '/onboarding'
    | '/payment-success'
    | '/pricing'
    | '/privacy'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/upgrade'
    | '/about/product'
    | '/dashboard/applications'
    | '/dashboard/career-profile'
    | '/dashboard/jobs'
    | '/dashboard/resume'
    | '/dashboard/resume-tailor'
    | '/dashboard/settings'
    | '/mission-control/company-replay'
    | '/mission-control/decision-engine'
    | '/mission-control/leakage-explorer'
    | '/mission-control/telemetry'
    | '/mission-control/unknown'
    | '/dashboard/'
    | '/mission-control/'
    | '/dashboard/jobs/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HealthRoute: typeof HealthRoute
  LegalRoute: typeof LegalRoute
  MissionControlRoute: typeof MissionControlRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  UpgradeRoute: typeof UpgradeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-control': {
      id: '/mission-control'
      path: '/mission-control'
      fullPath: '/mission-control'
      preLoaderRoute: typeof MissionControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-control/': {
      id: '/mission-control/'
      path: '/'
      fullPath: '/mission-control/'
      preLoaderRoute: typeof MissionControlIndexRouteImport
      parentRoute: typeof MissionControlRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/mission-control/unknown': {
      id: '/mission-control/unknown'
      path: '/unknown'
      fullPath: '/mission-control/unknown'
      preLoaderRoute: typeof MissionControlUnknownRouteImport
      parentRoute: typeof MissionControlRoute
    }
    '/mission-control/telemetry': {
      id: '/mission-control/telemetry'
      path: '/telemetry'
      fullPath: '/mission-control/telemetry'
      preLoaderRoute: typeof MissionControlTelemetryRouteImport
      parentRoute: typeof MissionControlRoute
    }
    '/mission-control/leakage-explorer': {
      id: '/mission-control/leakage-explorer'
      path: '/leakage-explorer'
      fullPath: '/mission-control/leakage-explorer'
      preLoaderRoute: typeof MissionControlLeakageExplorerRouteImport
      parentRoute: typeof MissionControlRoute
    }
    '/mission-control/decision-engine': {
      id: '/mission-control/decision-engine'
      path: '/decision-engine'
      fullPath: '/mission-control/decision-engine'
      preLoaderRoute: typeof MissionControlDecisionEngineRouteImport
      parentRoute: typeof MissionControlRoute
    }
    '/mission-control/company-replay': {
      id: '/mission-control/company-replay'
      path: '/company-replay'
      fullPath: '/mission-control/company-replay'
      preLoaderRoute: typeof MissionControlCompanyReplayRouteImport
      parentRoute: typeof MissionControlRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/resume-tailor': {
      id: '/dashboard/resume-tailor'
      path: '/resume-tailor'
      fullPath: '/dashboard/resume-tailor'
      preLoaderRoute: typeof DashboardResumeTailorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/resume': {
      id: '/dashboard/resume'
      path: '/resume'
      fullPath: '/dashboard/resume'
      preLoaderRoute: typeof DashboardResumeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jobs': {
      id: '/dashboard/jobs'
      path: '/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof DashboardJobsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/career-profile': {
      id: '/dashboard/career-profile'
      path: '/career-profile'
      fullPath: '/dashboard/career-profile'
      preLoaderRoute: typeof DashboardCareerProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/applications': {
      id: '/dashboard/applications'
      path: '/applications'
      fullPath: '/dashboard/applications'
      preLoaderRoute: typeof DashboardApplicationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/about/product': {
      id: '/about/product'
      path: '/product'
      fullPath: '/about/product'
      preLoaderRoute: typeof AboutProductRouteImport
      parentRoute: typeof AboutRoute
    }
    '/dashboard/jobs/$jobId': {
      id: '/dashboard/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/dashboard/jobs/$jobId'
      preLoaderRoute: typeof DashboardJobsJobIdRouteImport
      parentRoute: typeof DashboardJobsRoute
    }
  }
}

interface AboutRouteChildren {
  AboutProductRoute: typeof AboutProductRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutProductRoute: AboutProductRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface DashboardJobsRouteChildren {
  DashboardJobsJobIdRoute: typeof DashboardJobsJobIdRoute
}

const DashboardJobsRouteChildren: DashboardJobsRouteChildren = {
  DashboardJobsJobIdRoute: DashboardJobsJobIdRoute,
}

const DashboardJobsRouteWithChildren = DashboardJobsRoute._addFileChildren(
  DashboardJobsRouteChildren,
)

interface DashboardRouteChildren {
  DashboardApplicationsRoute: typeof DashboardApplicationsRoute
  DashboardCareerProfileRoute: typeof DashboardCareerProfileRoute
  DashboardJobsRoute: typeof DashboardJobsRouteWithChildren
  DashboardResumeRoute: typeof DashboardResumeRoute
  DashboardResumeTailorRoute: typeof DashboardResumeTailorRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardApplicationsRoute: DashboardApplicationsRoute,
  DashboardCareerProfileRoute: DashboardCareerProfileRoute,
  DashboardJobsRoute: DashboardJobsRouteWithChildren,
  DashboardResumeRoute: DashboardResumeRoute,
  DashboardResumeTailorRoute: DashboardResumeTailorRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface MissionControlRouteChildren {
  MissionControlCompanyReplayRoute: typeof MissionControlCompanyReplayRoute
  MissionControlDecisionEngineRoute: typeof MissionControlDecisionEngineRoute
  MissionControlLeakageExplorerRoute: typeof MissionControlLeakageExplorerRoute
  MissionControlTelemetryRoute: typeof MissionControlTelemetryRoute
  MissionControlUnknownRoute: typeof MissionControlUnknownRoute
  MissionControlIndexRoute: typeof MissionControlIndexRoute
}

const MissionControlRouteChildren: MissionControlRouteChildren = {
  MissionControlCompanyReplayRoute: MissionControlCompanyReplayRoute,
  MissionControlDecisionEngineRoute: MissionControlDecisionEngineRoute,
  MissionControlLeakageExplorerRoute: MissionControlLeakageExplorerRoute,
  MissionControlTelemetryRoute: MissionControlTelemetryRoute,
  MissionControlUnknownRoute: MissionControlUnknownRoute,
  MissionControlIndexRoute: MissionControlIndexRoute,
}

const MissionControlRouteWithChildren = MissionControlRoute._addFileChildren(
  MissionControlRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HealthRoute: HealthRoute,
  LegalRoute: LegalRoute,
  MissionControlRoute: MissionControlRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  UpgradeRoute: UpgradeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
