/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MissionControlRouteImport } from './routes/mission-control'
import { Route as HealthRouteImport } from './routes/health'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MissionControlIndexRouteImport } from './routes/mission-control/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as MissionControlUnknownRouteImport } from './routes/mission-control/unknown'
import { Route as MissionControlTelemetryRouteImport } from './routes/mission-control/telemetry'
import { Route as MissionControlLeakageExplorerRouteImport } from './routes/mission-control/leakage-explorer'
import { Route as MissionControlDecisionEngineRouteImport } from './routes/mission-control/decision-engine'
import { Route as MissionControlCompanyReplayRouteImport } from './routes/mission-control/company-replay'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardResumeRouteImport } from './routes/dashboard/resume'
import { Route as DashboardPipelineRouteImport } from './routes/dashboard/pipeline'
import { Route as DashboardJobsRouteImport } from './routes/dashboard/jobs'
import { Route as DashboardCompaniesRouteImport } from './routes/dashboard/companies'
import { Route as DashboardApplicationsRouteImport } from './routes/dashboard/applications'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as DashboardJobsJobIdRouteImport } from './routes/dashboard/jobs.$jobId'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionControlRoute = MissionControlRouteImport.update({
  id: '/mission-control',
  path: '/mission-control',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionControlIndexRoute = MissionControlIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MissionControlRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const MissionControlUnknownRoute = MissionControlUnknownRouteImport.update({
  id: '/unknown',
  path: '/unknown',
  getParentRoute: () => MissionControlRoute,
} as any)
const MissionControlTelemetryRoute = MissionControlTelemetryRouteImport.update({
  id: '/telemetry',
  path: '/telemetry',
  getParentRoute: () => MissionControlRoute,
} as any)
const MissionControlLeakageExplorerRoute =
  MissionControlLeakageExplorerRouteImport.update({
    id: '/leakage-explorer',
    path: '/leakage-explorer',
    getParentRoute: () => MissionControlRoute,
  } as any)
const MissionControlDecisionEngineRoute =
  MissionControlDecisionEngineRouteImport.update({
    id: '/decision-engine',
    path: '/decision-engine',
    getParentRoute: () => MissionControlRoute,
  } as any)
const MissionControlCompanyReplayRoute =
  MissionControlCompanyReplayRouteImport.update({
    id: '/company-replay',
    path: '/company-replay',
    getParentRoute: () => MissionControlRoute,
  } as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResumeRoute = DashboardResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPipelineRoute = DashboardPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJobsRoute = DashboardJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCompaniesRoute = DashboardCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApplicationsRoute = DashboardApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJobsJobIdRoute = DashboardJobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => DashboardJobsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/health': typeof HealthRoute
  '/mission-control': typeof MissionControlRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/upload': typeof UploadRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/companies': typeof DashboardCompaniesRoute
  '/dashboard/jobs': typeof DashboardJobsRouteWithChildren
  '/dashboard/pipeline': typeof DashboardPipelineRoute
  '/dashboard/resume': typeof DashboardResumeRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/mission-control/company-replay': typeof MissionControlCompanyReplayRoute
  '/mission-control/decision-engine': typeof MissionControlDecisionEngineRoute
  '/mission-control/leakage-explorer': typeof MissionControlLeakageExplorerRoute
  '/mission-control/telemetry': typeof MissionControlTelemetryRoute
  '/mission-control/unknown': typeof MissionControlUnknownRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/mission-control/': typeof MissionControlIndexRoute
  '/dashboard/jobs/$jobId': typeof DashboardJobsJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/health': typeof HealthRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/upload': typeof UploadRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/companies': typeof DashboardCompaniesRoute
  '/dashboard/jobs': typeof DashboardJobsRouteWithChildren
  '/dashboard/pipeline': typeof DashboardPipelineRoute
  '/dashboard/resume': typeof DashboardResumeRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/mission-control/company-replay': typeof MissionControlCompanyReplayRoute
  '/mission-control/decision-engine': typeof MissionControlDecisionEngineRoute
  '/mission-control/leakage-explorer': typeof MissionControlLeakageExplorerRoute
  '/mission-control/telemetry': typeof MissionControlTelemetryRoute
  '/mission-control/unknown': typeof MissionControlUnknownRoute
  '/dashboard': typeof DashboardIndexRoute
  '/mission-control': typeof MissionControlIndexRoute
  '/dashboard/jobs/$jobId': typeof DashboardJobsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/health': typeof HealthRoute
  '/mission-control': typeof MissionControlRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/upload': typeof UploadRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/companies': typeof DashboardCompaniesRoute
  '/dashboard/jobs': typeof DashboardJobsRouteWithChildren
  '/dashboard/pipeline': typeof DashboardPipelineRoute
  '/dashboard/resume': typeof DashboardResumeRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/mission-control/company-replay': typeof MissionControlCompanyReplayRoute
  '/mission-control/decision-engine': typeof MissionControlDecisionEngineRoute
  '/mission-control/leakage-explorer': typeof MissionControlLeakageExplorerRoute
  '/mission-control/telemetry': typeof MissionControlTelemetryRoute
  '/mission-control/unknown': typeof MissionControlUnknownRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/mission-control/': typeof MissionControlIndexRoute
  '/dashboard/jobs/$jobId': typeof DashboardJobsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/health'
    | '/mission-control'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/upload'
    | '/dashboard/admin'
    | '/dashboard/analytics'
    | '/dashboard/applications'
    | '/dashboard/companies'
    | '/dashboard/jobs'
    | '/dashboard/pipeline'
    | '/dashboard/resume'
    | '/dashboard/settings'
    | '/mission-control/company-replay'
    | '/mission-control/decision-engine'
    | '/mission-control/leakage-explorer'
    | '/mission-control/telemetry'
    | '/mission-control/unknown'
    | '/dashboard/'
    | '/mission-control/'
    | '/dashboard/jobs/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/health'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/upload'
    | '/dashboard/admin'
    | '/dashboard/analytics'
    | '/dashboard/applications'
    | '/dashboard/companies'
    | '/dashboard/jobs'
    | '/dashboard/pipeline'
    | '/dashboard/resume'
    | '/dashboard/settings'
    | '/mission-control/company-replay'
    | '/mission-control/decision-engine'
    | '/mission-control/leakage-explorer'
    | '/mission-control/telemetry'
    | '/mission-control/unknown'
    | '/dashboard'
    | '/mission-control'
    | '/dashboard/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/health'
    | '/mission-control'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/upload'
    | '/dashboard/admin'
    | '/dashboard/analytics'
    | '/dashboard/applications'
    | '/dashboard/companies'
    | '/dashboard/jobs'
    | '/dashboard/pipeline'
    | '/dashboard/resume'
    | '/dashboard/settings'
    | '/mission-control/company-replay'
    | '/mission-control/decision-engine'
    | '/mission-control/leakage-explorer'
    | '/mission-control/telemetry'
    | '/mission-control/unknown'
    | '/dashboard/'
    | '/mission-control/'
    | '/dashboard/jobs/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FaqRoute: typeof FaqRoute
  HealthRoute: typeof HealthRoute
  MissionControlRoute: typeof MissionControlRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-control': {
      id: '/mission-control'
      path: '/mission-control'
      fullPath: '/mission-control'
      preLoaderRoute: typeof MissionControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-control/': {
      id: '/mission-control/'
      path: '/'
      fullPath: '/mission-control/'
      preLoaderRoute: typeof MissionControlIndexRouteImport
      parentRoute: typeof MissionControlRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/mission-control/unknown': {
      id: '/mission-control/unknown'
      path: '/unknown'
      fullPath: '/mission-control/unknown'
      preLoaderRoute: typeof MissionControlUnknownRouteImport
      parentRoute: typeof MissionControlRoute
    }
    '/mission-control/telemetry': {
      id: '/mission-control/telemetry'
      path: '/telemetry'
      fullPath: '/mission-control/telemetry'
      preLoaderRoute: typeof MissionControlTelemetryRouteImport
      parentRoute: typeof MissionControlRoute
    }
    '/mission-control/leakage-explorer': {
      id: '/mission-control/leakage-explorer'
      path: '/leakage-explorer'
      fullPath: '/mission-control/leakage-explorer'
      preLoaderRoute: typeof MissionControlLeakageExplorerRouteImport
      parentRoute: typeof MissionControlRoute
    }
    '/mission-control/decision-engine': {
      id: '/mission-control/decision-engine'
      path: '/decision-engine'
      fullPath: '/mission-control/decision-engine'
      preLoaderRoute: typeof MissionControlDecisionEngineRouteImport
      parentRoute: typeof MissionControlRoute
    }
    '/mission-control/company-replay': {
      id: '/mission-control/company-replay'
      path: '/company-replay'
      fullPath: '/mission-control/company-replay'
      preLoaderRoute: typeof MissionControlCompanyReplayRouteImport
      parentRoute: typeof MissionControlRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/resume': {
      id: '/dashboard/resume'
      path: '/resume'
      fullPath: '/dashboard/resume'
      preLoaderRoute: typeof DashboardResumeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pipeline': {
      id: '/dashboard/pipeline'
      path: '/pipeline'
      fullPath: '/dashboard/pipeline'
      preLoaderRoute: typeof DashboardPipelineRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jobs': {
      id: '/dashboard/jobs'
      path: '/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof DashboardJobsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/companies': {
      id: '/dashboard/companies'
      path: '/companies'
      fullPath: '/dashboard/companies'
      preLoaderRoute: typeof DashboardCompaniesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/applications': {
      id: '/dashboard/applications'
      path: '/applications'
      fullPath: '/dashboard/applications'
      preLoaderRoute: typeof DashboardApplicationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jobs/$jobId': {
      id: '/dashboard/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/dashboard/jobs/$jobId'
      preLoaderRoute: typeof DashboardJobsJobIdRouteImport
      parentRoute: typeof DashboardJobsRoute
    }
  }
}

interface DashboardJobsRouteChildren {
  DashboardJobsJobIdRoute: typeof DashboardJobsJobIdRoute
}

const DashboardJobsRouteChildren: DashboardJobsRouteChildren = {
  DashboardJobsJobIdRoute: DashboardJobsJobIdRoute,
}

const DashboardJobsRouteWithChildren = DashboardJobsRoute._addFileChildren(
  DashboardJobsRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardApplicationsRoute: typeof DashboardApplicationsRoute
  DashboardCompaniesRoute: typeof DashboardCompaniesRoute
  DashboardJobsRoute: typeof DashboardJobsRouteWithChildren
  DashboardPipelineRoute: typeof DashboardPipelineRoute
  DashboardResumeRoute: typeof DashboardResumeRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardApplicationsRoute: DashboardApplicationsRoute,
  DashboardCompaniesRoute: DashboardCompaniesRoute,
  DashboardJobsRoute: DashboardJobsRouteWithChildren,
  DashboardPipelineRoute: DashboardPipelineRoute,
  DashboardResumeRoute: DashboardResumeRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface MissionControlRouteChildren {
  MissionControlCompanyReplayRoute: typeof MissionControlCompanyReplayRoute
  MissionControlDecisionEngineRoute: typeof MissionControlDecisionEngineRoute
  MissionControlLeakageExplorerRoute: typeof MissionControlLeakageExplorerRoute
  MissionControlTelemetryRoute: typeof MissionControlTelemetryRoute
  MissionControlUnknownRoute: typeof MissionControlUnknownRoute
  MissionControlIndexRoute: typeof MissionControlIndexRoute
}

const MissionControlRouteChildren: MissionControlRouteChildren = {
  MissionControlCompanyReplayRoute: MissionControlCompanyReplayRoute,
  MissionControlDecisionEngineRoute: MissionControlDecisionEngineRoute,
  MissionControlLeakageExplorerRoute: MissionControlLeakageExplorerRoute,
  MissionControlTelemetryRoute: MissionControlTelemetryRoute,
  MissionControlUnknownRoute: MissionControlUnknownRoute,
  MissionControlIndexRoute: MissionControlIndexRoute,
}

const MissionControlRouteWithChildren = MissionControlRoute._addFileChildren(
  MissionControlRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FaqRoute: FaqRoute,
  HealthRoute: HealthRoute,
  MissionControlRoute: MissionControlRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
