target_roles:
  - associate_product_manager
  - product_manager
  - product_analyst
  - founders_office
  - chief_of_staff
  - ai_engineer
  - machine_learning_engineer
  - software_engineer
  - data_scientist

experience:
  max_years: 2

locations:
  - India
  - Remote

preferred_companies:
  priority:
    - P0
    - P1

remote_preference: True

exclude_keywords:
  - senior
  - staff
  - principal
  - director
  - vp
  - manager (5+ years)
  - lead
  - head
